language: python
python:
    - "3.6"
install:
    - cd API
    - pip install -r requirements.txt
script:
    - cd v1
    - nosetests --with-coverage --cover-package=routes tests/*
    - ../cd v2
    - nosetests --with-coverage --cover-package=routes tests/*
# run coverage tests
after_success:
  - coveralls
  - codecov --token=0634ba86-efae-4b82-822d-a55ec7ceec7b
