language: python
python:
    - "3.6"
install:
    - cd API
    - source travis.sh
    - pip install -r requirements.txt
script:
    - cp .envexample .env
    - nosetests --with-coverage --cover-package=routes tests/*
# run coverage tests
after_success:
    - coveralls
