language: python
python:
    - "3.6"
install:
    - cd API
    - pip install -r requirements.txt
script:
    - nosetests --with-coverage --cover-package=routes tests/*
# run coverage tests
after_success:
  - coveralls
  - bash < (curl -s https://codecov.io/bash)
