FORMAT: 1A
HOST: https://maintenance-tracker-api.herokuapp.com/api/v1

# Maintenance Tracker

## Project Overview
Maintenance Tracker App is an application that provides users with the ability to reach out to operations or repairs department regarding repair or maintenance requests and monitor the status of their request.
## Required Features
1. Users can create an account and log in.
2. The users should be able to make maintenance or repairs request.
3. An admin should be able to approve/reject a repair/maintenance request.
4. The admin should be able to mark request as resolved once it is done.
5. The admin should be able to view all maintenance/repairs requests on the application
6. The admin should be able to filter requests
7. The user can view all his/her requests

Making API calls will require the following header
```
Content-Type : application/json
```
After authentication, the rest of the endpoints will require to include the bearer token that is sent with the login reponse.
```
Authentication: Bearer [Token]
```

## Registration [/users/register]

### Sign up [POST]

Creates a new user account. Once the user has successfully signed up, they can login with their username and password.

+ Request (application/json)

        {
            "firstname": "Moses",
            "lastname": "Gitau",
            "email": "gitaumoses@gmail.com",
            "password": "password",
            "username": "gitaumoses"
        }
        
+ Response 201 (application/json)

        {
            "data": {
                "user": {
                     "email": "gitaumoses@gmail.com",
                    "firstname": "Moses",
                    "id": 2,
                    "lastname": "Gitau",
                    "profile_picture": "",
                    "username": "gitaumoses"
                }
            },
            "status": "success"
        }

## Login [/users/login]

### Sign in[POST]

The user can login with their username and password. The response includes a token which will be used in subsequent requests.

+ Request (application/json)

        {
            "username": "gitaumoses"
            "password": "password"
        }
        
+ Response 200 (application/json)

        {
            "data": {
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Mjc4Njc5MjgsIm5iZiI6MTUyNzg2NzkyOCwianRpIjoiYjJhOGE3OTYtNGE5MS00YzU0LThhY2ItZmU5NDQ3NDNiYjg0IiwiZXhwIjoxNTI3ODY4ODI4LCJpZGVudGl0eSI6ImdpdGF1bW9zZXMiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.URM1Yr9ziOmB4w5HORZElhJDP7RCd_6wC_0ERQA9aAE",
                "user": {
                    "email": "gitaumoses@gmail.com",
                    "firstname": "Moses",
                    "id": 2,
                    "lastname": "Gitau",
                    "profile_picture": "",
                    "username": "gitaumoses"
                }
            },
            "status": "success"
        }

## Admin Login [/admin/login]

### Sign in[POST]

The admin can sign in with the default username and password for admins. This can be changed later when the admin is already logged in.

+ Request (application/json)

        {
            "username": "admin",
            "password": "admin"
        }
        
+ Response 200 (application/json)

        {
            "data": {
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Mjc4NjgyNTUsIm5iZiI6MTUyNzg2ODI1NSwianRpIjoiOWI2MTk4YzItZDlmOC00MWI0LTgwZGItZWU5ODA2ZGEzMzEyIiwiZXhwIjoxNTI3ODY5MTU1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIn0.4OGsm9mljsQcfKzWyWXby70X5YduGIBwzSORs23IwOI",
                "user": {
                    "email": "gitaumoses4@gmail.com",
                    "firstname": "Moses",
                    "id": 1,
                    "lastname": "Gitau",
                    "profile_picture": "",
                    "username": "admin"
                }
            },
            "status": "success"
        }

## User Maintenance Requests [/users/requests]

### Create a maintenance/repair request[POST]

The user can create a maintenance/repair request. This will be verified by the admin, who will accept or reject it.

+ Request (application/json)

        {
            "product_name": "Samsung TV",
            "description" : "Has a broken screen",
            "photo"       : "link to image"
        }

+ Response 201 (application/json)

        {
            "data": {
                "request": {
                    "created_at": "2018-06-01 18:58:26",
                    "created_by": {
                        "created_at": "2018-06-01 18:38:01",
                        "email": "gitaumoses@gmail.com",
                        "firstname": "Moses",
                        "id": 2,
                        "lastname": "Gitau",
                        "password": "$2b$12$UBo5DpLOXuGi/qmsHS0FdOnqyu/7ypLvDL3Qv3vo1Q7R.VS1VUiEy",
                        "profile_picture": "",
                        "role": "User",
                        "username": "gitaumoses"
                    },
                    "description": "Has a broken screen",
                    "id": 1,
                    "photo": "link to image",
                    "product_name": "Samsung TV",
                    "status": "Pending"
                }
            },
            "status": "success"
        }
        
### Get all requests[GET]
+ Response 200 (application/json)

        {
            "data": {
                "requests": [
                    {
                        "created_at": "2018-06-01 19:04:29",
                        "created_by": {
                            "created_at": "2018-06-01 19:04:05",
                            "email": "gitaumoses@gmail.com",
                            "firstname": "Moses",
                            "id": 2,
                            "lastname": "Gitau",
                            "password": "$2b$12$xkklWUS4lja/r8N0MMHQmuKC..grQK9Nvx.BcxE7FoZTG6OCY.m2.",
                            "profile_picture": "",
                            "role": "User",
                            "username": "gitaumoses"
                        },
                        "description": "Has a broken screen",
                        "id": 1,
                        "photo": "link to image",
                        "product_name": "Samsung TV",
                        "status": "Pending"
                    }
                ],
                "total_requests": 1
            },
            "status": "success"
        }

## User Modify Request [/users/request/{request_id}]
+ Parameters
    + request_id (integer) - Id of the request the user wants to get details.
    
### Get request by id[GET]
The user can get the details of a request given the request id.

+ Response 200 (application/json)

        {
            "data": {
                "request": {
                    "created_at": "2018-06-01 19:10:53",
                    "created_by": {
                        "created_at": "2018-06-01 19:10:40",
                        "email": "gitaumoses@gmail.com",
                        "firstname": "Moses",
                        "id": 2,
                        "lastname": "Gitau",
                        "password": "$2b$12$IgdqXqSZHW.yguOCOUNAiuSp7FMWHHfm9.xum.cLRtaRBVwEWmQF2",
                        "profile_picture": "",
                        "role": "User",
                        "username": "gitaumoses"
                    },
                    "description": "Has a broken screen",
                    "id": 2,
                    "photo": "link to image",
                    "product_name": "Samsung TV",
                    "status": "Pending"
                }
            },
            "status": "success"
        }
        
### Update Request[PUT]
The user can update the details of a request

+ Request (application/json)

        {
            "product_name": "Samsung LED TV",
            "description": "New Description"
        }
        
+ Response 200 (application/json)

        {
            "data": {
                "request": {
                    "created_at": "2018-06-01 19:10:53",
                    "created_by": {
                        "created_at": "2018-06-01 19:10:40",
                        "email": "gitaumoses@gmail.com",
                        "firstname": "Moses",
                        "id": 2,
                        "lastname": "Gitau",
                        "password": "$2b$12$IgdqXqSZHW.yguOCOUNAiuSp7FMWHHfm9.xum.cLRtaRBVwEWmQF2",
                        "profile_picture": "",
                        "role": "User",
                        "username": "gitaumoses"
                    },
                    "description": "New description",
                    "id": 2,
                    "photo": "link to image",
                    "product_name": "Samsung LED tv",
                    "status": "Pending"
                }
            },
            "status": "success"
        }
        
## Admin Maintenance Requests [/admin/requests/]

### Get all Requests[GET]

The admin can get all available requests for all the users.

+ Response 200 (application/json)

        {
            "data": {
                "requests": [
                    {
                        "created_at": "2018-06-01 19:04:29",
                        "created_by": {
                            "created_at": "2018-06-01 19:04:05",
                            "email": "gitaumoses@gmail.com",
                            "firstname": "Moses",
                            "id": 2,
                            "lastname": "Gitau",
                            "password": "$2b$12$xkklWUS4lja/r8N0MMHQmuKC..grQK9Nvx.BcxE7FoZTG6OCY.m2.",
                            "profile_picture": "",
                            "role": "User",
                            "username": "gitaumoses"
                        },
                        "description": "Has a broken screen",
                        "id": 1,
                        "photo": "link to image",
                        "product_name": "Samsung TV",
                        "status": "Pending"
                    }
                ],
                "total_requests": 1
            },
            "status": "success"
        }

## Admin Update or view  Request [/admin/requests/{request_id}]

+ Parameters
    + request_id (integer) - The ID of the request the admin would like to update.
    
### Change Request Status[PUT]

+ Request (application/json)
        
        {
            "status": "Approved"
        }

+ Response 200 (application/json)

        {
            "data": {
                "request": {
                    "created_at": "2018-06-01 20:15:02",
                    "created_by": {
                        "created_at": "2018-06-01 20:114:03",
                        "email": "gitaumoses4@gmail.com",
                        "firstname": "Moses",
                        "id": 1,
                        "lastname": "Gitau",
                        "password": "$2b$12$xf6MCp/7SgARSixxAXWg.ub7Gz2EnSvhkBw8sl8okpZBxuX4P8RyG",
                        "profile_picture": "",
                        "role": "Administrator",
                        "username": "admin"
                    },
                    "description": "Has a broken screen",
                    "id": 1,
                    "photo": "link to image",
                    "product_name": "Samsung TV",
                    "status": "Approved"
                }
            },
            "status": "success"
        }

### View a request details [GET]

An admin can query the details of a particular request.

+ Response 200 (application/json)

        {
            "data": {
                "request": {
                    "created_at": "2018-06-01 20:24:29",
                    "created_by": {
                        "created_at": "2018-06-01 20:24:22",
                        "email": "gitaumoses4@gmail.com",
                        "firstname": "Moses",
                        "id": 1,
                        "lastname": "Gitau",
                        "password": "$2b$12$ro6gw3GWYIDnNMih9wRv.ufAuOhYKZ0yPeQK9Jj/oKnsMJ/xTpcX.",
                        "profile_picture": "",
                        "role": "Administrator",
                        "username": "admin"
                    },
                    "description": "Has a broken screen",
                    "id": 1,
                    "photo": "link to image",
                    "product_name": "Samsung TV",
                    "status": "Pending"
                }
            },
            "status": "success"
        }

## Provide Feedback [/admin/requests/{request_id}/feedback]

### Admin to provide feedback [POST]

Admin will be able to provide feedback on a particular request.

+ Request (application/json)

        {
            "message": "Here is your feedback"
        }
+ Response 201 (application/json)

        {
            "data": {
                "feedback": {
                    "admin": {
                        "created_at": "2018-06-01 20:24:22",
                        "email": "gitaumoses4@gmail.com",
                        "firstname": "Moses",
                        "id": 1,
                        "lastname": "Gitau",
                        "password": "$2b$12$ro6gw3GWYIDnNMih9wRv.ufAuOhYKZ0yPeQK9Jj/oKnsMJ/xTpcX.",
                        "profile_picture": "",
                        "role": "Administrator",
                        "updated_at": "2018-06-01 20:24:22",
                        "username": "admin"
                    },
                    "created_at": "2018-06-01 20:29:51",
                    "id": 1,
                    "message": "Here is your feedback",
                    "request": {
                        "created_at": "2018-06-01 20:24:29",
                        "created_by": {
                            "created_at": "2018-06-01 20:24:22",
                            "email": "gitaumoses4@gmail.com",
                            "firstname": "Moses",
                            "id": 1,
                            "lastname": "Gitau",
                            "password": "$2b$12$ro6gw3GWYIDnNMih9wRv.ufAuOhYKZ0yPeQK9Jj/oKnsMJ/xTpcX.",
                            "profile_picture": "",
                            "role": "Administrator",
                            "updated_at": "2018-06-01 20:24:22",
                            "username": "admin"
                        },
                        "description": "Has a broken screen",
                        "id": 1,
                        "photo": "link to image",
                        "product_name": "Samsung TV",
                        "status": "Pending",
                        "updated_at": "2018-06-01 20:24:22"
                    },
                    "updated_at": "2018-06-01 20:24:22"
                }
            },
            "status": "success"
        }

## User Request feedback [/users/requests/{request_id}/feedback]

+ Parameters
    + request_id (integer) - The id of the request to get feedback details.
    
### Get feedback for request[GET]

+ Response 200 (application/json)

        {
            "data": {
                "feedback": [
                    {
                        "admin": {
                            "created_at": "2018-06-01 20:36:59",
                            "email": "gitaumoses4@gmail.com",
                            "firstname": "Moses",
                            "id": 1,
                            "lastname": "Gitau",
                            "password": "$2b$12$nLKQheHWtp6Sn8NNAS5Ua.3z90xy58ruV3WFqdp58etRCVZkPlToG",
                            "profile_picture": "",
                            "role": "Administrator",
                            "updated_at": "2018-06-01 20:36:59",
                            "username": "admin"
                        },
                        "created_at": "2018-06-01 20:37:29",
                        "id": 1,
                        "message": "Here is your feedback",
                        "request": {
                            "created_at": "2018-06-01 20:37:13",
                            "created_by": {
                                "created_at": "2018-06-01 20:37:02",
                                "email": "gitaumoses@gmail.com",
                                "firstname": "Moses",
                                "id": 2,
                                "lastname": "Gitau",
                                "password": "$2b$12$zP.53BZ0axpp6rLwRxtcCe9s0X5xTFOdIL50Nt6g57P8rzftyO39S",
                                "profile_picture": "",
                                "role": "User",
                                "updated_at": "2018-06-01 20:36:59",
                                "username": "gitaumoses"
                            },
                            "description": "Has a broken screen",
                            "id": 1,
                            "photo": "link to image",
                            "product_name": "Samsung TV",
                            "status": "Pending",
                            "updated_at": "2018-06-01 20:36:59"
                        },
                        "updated_at": "2018-06-01 20:36:59"
                    }
                ]
            },
            "status": "success"
        }

## User Information [/users/details]

### Get User details [GET]
Get's the details of the logged in user.

+ Response 200 (application/json)

        {
            "data": {
                "user": {
                    "email": "gitaumoses@gmail.com",
                    "firstname": "Moses",
                    "id": 2,
                    "lastname": "Gitau",
                    "profile_picture": "",
                    "username": "gitaumoses"
                }
            },
            "status": "success"
        }

## Send Notifications [/admin/users/{user_id}/notifications]

+ Parameter
    + user_id (integer) - the ID of the user to send the notification to.
    
### Send notification to user[POST]

Sends a notification to a particular user.

+ Request (application/json)
        
        {
            "message": "You have a notification"
        }
        
+ Response 201 (application/json)

        {
            "data": {
                "notification": {
                    "admin": {
                        "created_at": "2018-06-01 20:36:59",
                        "email": "gitaumoses4@gmail.com",
                        "firstname": "Moses",
                        "id": 1,
                        "lastname": "Gitau",
                        "password": "$2b$12$nLKQheHWtp6Sn8NNAS5Ua.3z90xy58ruV3WFqdp58etRCVZkPlToG",
                        "profile_picture": "",
                        "role": "Administrator",
                        "updated_at": "2018-06-01 20:36:59",
                        "username": "admin"
                    },
                    "created_at": "2018-06-01 20:44:33",
                    "id": 1,
                    "message": "You have a notification",
                    "read": false,
                    "updated_at": "2018-06-01 20:36:59",
                    "user": {
                        "created_at": "2018-06-01 20:36:59",
                        "email": "gitaumoses4@gmail.com",
                        "firstname": "Moses",
                        "id": 1,
                        "lastname": "Gitau",
                        "password": "$2b$12$nLKQheHWtp6Sn8NNAS5Ua.3z90xy58ruV3WFqdp58etRCVZkPlToG",
                        "profile_picture": "",
                        "role": "Administrator",
                        "updated_at": "2018-06-01 20:36:59",
                        "username": "admin"
                    }
                }
            },
            "status": "success"
        }
        
## Get Notifications [/users/notifications]

### Get all notifications[GET]

A user can get all the notifications sent to them.

+ Response 200 (application/json)

        {
            "data": {
                "notification_count": 1,
                "notifications": [
                    {
                        "admin": {
                            "created_at": "2018-06-01 20:47:15",
                            "email": "gitaumoses4@gmail.com",
                            "firstname": "Moses",
                            "id": 1,
                            "lastname": "Gitau",
                            "password": "$2b$12$MG6w.Ugv24b1jd5cD.fHZ./9Nm2a/rRuZCvEIpen2oxheotJ4DJIa",
                            "profile_picture": "",
                            "role": "Administrator",
                            "updated_at": "2018-06-01 20:47:15",
                            "username": "admin"
                        },
                        "created_at": "2018-06-01 20:48:34",
                        "id": 1,
                        "message": "You have a notification",
                        "read": false,
                        "updated_at": "2018-06-01 20:47:15",
                        "user": {
                            "created_at": "2018-06-01 20:47:58",
                            "email": "gitaumoses@gmail.com",
                            "firstname": "Moses",
                            "id": 2,
                            "lastname": "Gitau",
                            "password": "$2b$12$TlFShk.KTMSCEmdzubWmOOCassO38JzhuDbgW3krhJJCYneuwwkS6",
                            "profile_picture": "",
                            "role": "User",
                            "updated_at": "2018-06-01 20:47:15",
                            "username": "gitaumoses"
                        }
                    }
                ]
            },
            "status": "success"
        }
        
### Get or Update Single notification [/users/notifications/{notification_id}]

+ Parameters
    + notification_id (integer) - The ID of the notification.
    
#### Get notification by id [GET]

+ Response 200 (application/json)

        {
            "data": {
                "notification": {
                    "admin": {
                        "created_at": "2018-06-01 20:47:15",
                        "email": "gitaumoses4@gmail.com",
                        "firstname": "Moses",
                        "id": 1,
                        "lastname": "Gitau",
                        "password": "$2b$12$MG6w.Ugv24b1jd5cD.fHZ./9Nm2a/rRuZCvEIpen2oxheotJ4DJIa",
                        "profile_picture": "",
                        "role": "Administrator",
                        "updated_at": "2018-06-01 20:47:15",
                        "username": "admin"
                    },
                    "created_at": "2018-06-01 20:48:34",
                    "id": 1,
                    "message": "You have a notification",
                    "read": false,
                    "updated_at": "2018-06-01 20:47:15",
                    "user": {
                        "created_at": "2018-06-01 20:47:58",
                        "email": "gitaumoses@gmail.com",
                        "firstname": "Moses",
                        "id": 2,
                        "lastname": "Gitau",
                        "password": "$2b$12$TlFShk.KTMSCEmdzubWmOOCassO38JzhuDbgW3krhJJCYneuwwkS6",
                        "profile_picture": "",
                        "role": "User",
                        "updated_at": "2018-06-01 20:47:15",
                        "username": "gitaumoses"
                    }
                }
            },
            "status": "success"
        }

#### Set as seen [PUT]

This will mark the notification as seen by the user.

+ Response 200 (application/json)

        {
            "message": "Successfully marked as read",
            "status": "success"
        }