MAT: 1A
HOST: https://maintenance-tracker-api.herokuapp.com/

# Maintenance Tracker

## Project Overview
Maintenance Tracker App is an application that provides users with the ability to reach out to operations or repairs department regarding repair or maintenance requests and monitor the status of their request.
## Required Features
1. Users can create an account and log in.
2. The users should be able to make maintenance or repairs request.
3. An admin should be able to approve/reject a repair/maintenance request.
4. The admin should be able to mark request as resolved once it is done.
5. The admin should be able to view all maintenance/repairs requests on the application
6. The admin should be able to filter requests
7. The user can view all his/her requests


## Users [/api/v1/users/]

### Register [POST]

+ Request (application/json)
        {
            "firstname" : "John"
            "lastname:  : "Doe"
            "email"     : "johndoe@gmail.com"
            "password"  : "password"
        }
        
+ Response 201 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

